// General
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS'

// Playlist Actions
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const ADD_PLAYLIST_SONG = 'ADD_PLAYLIST_SONG'
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SONG = 'DELETE_PLAYLIST_SONG'

// Song Actions
export const ADD_SONG = 'ADD_SONG'
export const ADD_SONG_COMMENT = 'ADD_SONG_COMMENT'
export const DELETE_SONG_COMMENT = 'DELETE_SONG_COMMENT'
export const DELETE_SONG = 'DELETE_SONG'
export const FETCH_SONGS = 'FETCH_SONGS'

// Comment Actions
export const ADD_COMMENT = 'ADD_COMMENT'
export const BULK_COMMENTS_DELETE = 'BULK_COMMENTS_DELETE'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
