// sillyonly - "he streams for 14 days! can he do the 15?" (02/09/20)
// Playlist Actions
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const ADD_PLAYLIST_MEMBER = 'ADD_PLAYLIST_MEMBER'
export const ADD_PLAYLIST_SONG = 'ADD_PLAYLIST_SONG'
export const ADD_SONG_COMMENT = 'ADD_SONG_COMMENT'
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SONG = 'DELETE_PLAYLIST_SONG'
export const DELETE_SONG_COMMENT = 'DELETE_SONG_COMMENT'
export const HYDRATE_PLAYLISTS = 'HYDRATE_PLAYLISTS'
export const SET_CURRENT_PLAYLIST_ID = 'SET_CURRENT_PLAYLIST_ID'

// Song Actions
export const ADD_SONG = 'ADD_SONG'
export const DELETE_SONG = 'DELETE_SONG'
export const FETCH_SONGS = 'FETCH_SONGS'

// Comment Actions
export const ADD_COMMENT = 'ADD_COMMENT'
export const BULK_COMMENTS_DELETE = 'BULK_COMMENTS_DELETE'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'

// User Actions
export const SIGN_IN = 'SIGN_IN'
export const SET_INITIAL_USER_DATA = 'SET_INITIAL_USER_DATA'
export const ADD_PLAYLIST_TO_USER = 'ADD_PLAYLIST_TO_USER'
export const DELETE_PLAYLIST_FROM_USER = 'DELETE_PLAYLIST_FROM_USER'

// Members Action
export const ADD_MEMBER = 'ADD_MEMBER'
export const FETCH_MEMBERS = 'FETCH_MEMBERS'
